config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'courses#index'

  get '/about', to: 'static#about'
  get '/eula', to: 'static#eula'
  get '/terms', to: 'static#terms'
  get '/paymentaddendum', to: 'static#paymentaddendum'
  get '/privacy', to: 'static#privacy'
  get '/contact', to: 'static#contact'
  get '/license_agreement', to: 'static#license_agreement'
  get 'getting_paid', to: 'static#getting_paid'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'login', to: 'sessions#new'
  # get 'logout', to: 'sessions#destroy'
  get 'account', to: 'users#account'
  get 'profile', to: 'users#show'
  get 'search', to: 'videos#search'
  get 'test_login', to: 'sessions#test_login'
  get 'instructor_agreement', to: 'static#instructor_agreement'
  # get 'videos', to: 'videos#index'
  # get 'videos/new', to: 'videos#new', as: 'new_video'
  # post 'videos', to: 'videos#create'

  get 'sessions/:id', to: 'sessions#impersonate'


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :courses, shallow: true do
      member do
        post 'toggle_approval'
      end
      resources :sections do
        resources :videos do
          member do
            post 'toggle_approval'
          end
        end
      end
    end
    get 'sessions/:id', to: 'sessions#impersonate', as: "impersonate"
    get 'videos', to: 'videos#index'
  end

  resources :users
  resources :charges

  resources :plays
  resources :payments, only: [:new, :create]
  resources :courses, shallow: true do
    resources :sections do
      resources :videos do
        member do
          get 'download'
        end
      end
    end
  end

end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course, optional: true
  has_many :videos, { dependent: :destroy }, -> { order(position: :asc) }
  accepts_nested_attributes_for :videos
  acts_as_list scope: :course
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }


  def length_in_seconds
    videos.sum(:length_in_seconds)
  end

  def minutes_viewed
    seconds_viewed/60
  end

  def add_seconds_viewed(seconds)
    update(seconds_viewed: seconds_viewed + seconds)
  end

  def minutes_viewed
    seconds_viewed/60
  end

  def seconds_played
    videos.map { |video| video.plays.sum(:length_in_seconds) }.reduce(:+) || 0
  end

  def only_child?
    course.sections.count == 1
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminController
  def show
    @section = Section.find(params[:id])
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:update, :destroy, :show, :edit]
  before_action :set_course, only: [:new, :create]

  def index
  end

  def show
    @course = @section.course
    @videos = @section.videos
  end

  def new
    @section = @course.sections.new
  end

  def create
    @section = @course.sections.new(section_params)
    if @section.save
      flash[:success] = "Section added"
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def edit
    # @course = @section.course
  end

  def update
    if @section.update_attributes(section_params)
      flash[:success] = "Section updated"
      redirect_to section_path(@section)
    else
      render 'edit'
    end
  end

  def destroy
    @section.destroy
    flash[:success] = "Section deleted"
    redirect_to course_path(@section.course)
  end

  private

  def section_params
    params.require(:section).permit(:title, videos_attributes: [:id, :title, :position])
  end

  def set_section
    @section = Section.find(params[:id])
  end


  def set_course
    @course = Course.find(params[:course_id])
  end

end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/sections/show.html.erb
<div class="columns">
  <div class="column">
    <%= link_to @section.course.user.full_name, admin_user_path(@section.course.user) %> >
    <%= link_to @section.course.title, admin_course_path(@section.course) %> >
    <%= link_to @section.title, "#" %>
  </div>
</div>

<div class="columns">
  <div class="column is-6-desktop">
    <% if @video && @video.errors.any? %>
      <ul>
        <% @video.errors.full_messages.each do |msg| %>
          <li class="notification is-danger"><%= msg %></li>
        <% end %>
      </ul>
      <br>
    <% end %>

    <%= form_with scope: :video, url: admin_section_videos_path(@section) do |f| %>
      <div class="field">
        <div class="field">
        <%= f.label :wistia_id, class: "label" %>
        <div class="control">
          <%= f.text_field :wistia_id, class: "input" %>
        </div>
      </div>
        <%= f.label "Title", class: "label" %>
        <div class="control">
          <%= f.text_field :title, class: "input" %>
        </div>
      </div>
      
      <div class="field">
        <div class="control">
          <%= f.submit "Submit", class: "button is-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="columns">
  <div class="column">
    <table class="table">
      <thead>
        <th>Position</th>
        <th>Title</th>
        <th>Length</th>
        <th>Wistia ID</th>
        <th>Delivery ID</th>
      </thead>
      <tbody>
        <% @section.videos.order(:position).each do |video| %>
          <tr>
            <td><%= video.position %></td>
            <td><%= link_to video.title, video_path(video) %></td>
            <td><%= video.length_in_seconds %></td>
            <td><%= video.wistia_id %></td>
            <td><%= video.wistia_delivery_id %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>