config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'courses#index'

  get '/about', to: 'static#about'
  get '/eula', to: 'static#eula'
  get '/terms', to: 'static#terms'
  get '/paymentaddendum', to: 'static#paymentaddendum'
  get '/privacy', to: 'static#privacy'
  get '/contact', to: 'static#contact'
  get '/license_agreement', to: 'static#license_agreement'
  get 'getting_paid', to: 'static#getting_paid'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'login', to: 'sessions#new'
  # get 'logout', to: 'sessions#destroy'
  get 'account', to: 'users#account'
  get 'profile', to: 'users#show'
  get 'search', to: 'videos#search'
  get 'test_login', to: 'sessions#test_login'
  get 'instructor_agreement', to: 'static#instructor_agreement'
  # get 'videos', to: 'videos#index'
  # get 'videos/new', to: 'videos#new', as: 'new_video'
  # post 'videos', to: 'videos#create'

  get 'sessions/:id', to: 'sessions#impersonate'


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :courses, shallow: true do
      member do
        post 'toggle_approval'
      end
      resources :sections do
        resources :videos do
          member do
            post 'toggle_approval'
          end
        end
      end
    end
    get 'sessions/:id', to: 'sessions#impersonate', as: "impersonate"
    get 'videos', to: 'videos#index'
  end

  resources :users
  resources :charges

  resources :plays
  resources :payments, only: [:new, :create]
  resources :courses, shallow: true do
    resources :sections do
      resources :videos do
        member do
          get 'download'
        end
      end
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  belongs_to :section, optional: true
  has_many :plays
  acts_as_list scope: :section

  has_attached_file :download
  validates_attachment_content_type :download, content_type: ["application/zip", "text/plain"]


  validates :wistia_id, presence: true, uniqueness: true
  validates :wistia_delivery_id, presence: true, uniqueness: true
  validates :title, presence: true, length: { maximum: 50, minimum: 3 }
  validates :description, length: { maximum: 255 }

  scope :approved, -> { where(approved: true) }


  algoliasearch per_environment: true do
    attribute :title,
              :user_id,
              :seconds_viewed,
              :length_in_seconds,
              :wistia_id,
              :wistia_delivery_id,
              :created_at

    searchableAttributes ['title']
    customRanking ['desc(seconds_viewed)']
    hitsPerPage 30
  end

  def thumbnail_url
    folder = "https://embed-ssl.wistia.com/deliveries/"
    "#{folder}#{wistia_delivery_id}.jpg?image_crop_resized=300x169&image_quality=100&ssl=true"
  end

  def add_seconds_viewed(seconds)
    update(seconds_viewed: seconds_viewed + seconds)
  end


  def approve
    update(approved: true)
  end

  def unapprove
    update(approved: false)
  end

  def seconds_played
    plays.sum(:length_in_seconds) || 0
  end

  def minutes_viewed
    seconds_viewed/60
  end

  def previous
    ""
  end

  def next
    ""
  end



end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::AdminController


  def index
    @videos = Video.all.order(:id)
  end

  def new
  end

  def edit
  end

  def update
  end

  def create
    @section = Section.find(params[:section_id])
    @video = @section.videos.new(video_params)
    media = Wistia::Media.find(@video.wistia_id)
    @video.wistia_delivery_id = media.thumbnail.url[40, 40]
    @video.length_in_seconds = media.duration
    @video.user = @section.course.user

    if @video.save
      flash[:success] = "video saved"
    end

    redirect_back fallback_location: root_path

  end

  def destroy
  end

  def toggle_approval
    @video = Video.find(params[:id])
    if @video.approved
      @video.update(approved: false)
    else
      @video.update(approved: true)
    end
    redirect_to admin_videos_path
  end

  private

  def video_params
    params.require(:video).permit(:title, :wistia_id)
  end

end

app/controllers/videos_controller.rb
require 'wistia'
Wistia.password = ENV['WISTIA_SECRET_KEY']

class VideosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_video, only: [:show, :edit, :update, :destroy, :download]

  def index
    @videos = Video.approved.order(seconds_viewed: :desc).page(params[:page]).per(8)
  end

  def show
    if !user_signed_in?
      flash[:danger] = "You need to be logged in to watch videos"
      redirect_to root_url
    elsif current_user.balance < @video.length_in_seconds
      flash[:danger] = "You don't have enough minutes to view this video"
      redirect_to root_url
    else
      @play = Play.new
      @course = @video.section.course
    end
  end

  def new
    @section = Section.find(params[:section_id])
    @course = @section.course
    @video = @section.videos.new

    if Rails.env == 'development'
      @project = 'ma2vo0l9bd'
    elsif Rails.env == 'production'
      @project = '9hyra9x33g'
    elsif Rails.env == 'test'
      @project == 'ma2vo0l9bd'
    end
  end

  def create
    @section = Section.find(params[:section_id])
    @video = @section.videos.new(video_params)

    @video.user = current_user
    @video.image = @video.thumbnail_url
    if @video.save
      flash[:success] = "Video successfully submitted for approval"
      redirect_to section_path(@section)
    else
      render 'new'
    end
  end

  def edit
    @section = @video.section
    @course = @video.section.course
  end

  def update
    if @video.update_attributes(video_params)
      flash[:success] = "Video updated"
      redirect_to section_path(@video.section)
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    flash[:success] = "Video Deleted"
    redirect_to section_path(@video.section)
  end

  def search
    @query = params[:q]
    if params[:q].blank?
      redirect_back(fallback_location: root_url)
    else
      @videos = Video.approved.algolia_search(@query)
      render 'index'
    end
  end

  def download
    redirect_to @video.download.expiring_url(10)
  end


  private

  def video_params
    params.require(:video).permit(:title,
                                  :description,
                                  :length_in_seconds,
                                  :wistia_id,
                                  :wistia_delivery_id,
                                  :download)
  end

  def set_video
    @video = Video.find(params[:id])
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/edit.html.erb
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<% if @video.errors.any? %>
  <ul>
    <% @video.errors.full_messages.each do |msg| %>
      <li class="notification is-danger"><%= msg %></li>
    <% end %>
  </ul>
  <br>
<% end %>
<div class="columns">
  <div class="column is-6-desktop is-12-mobile">
    <%= form_for @video do |f| %>
      <div class="field">
        <div class="control">
          <%= f.text_field :title, class: "input", placeholder: "Title" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_area :description, class: "textarea", placeholder: "Short Video Description"%>
        </div>
      </div>
      <div class="field">
        <%= content_tag(:div, "&nbsp;", 
                    class: "wistia_embed wistia_async_#{@video.wistia_id} autoPlay=true",
                    id: "wistia_vid",
                    style: "height:360px;",
                    data: { video_id: @video.wistia_id }) %>
      </div>
      <div class="field">
        <%= f.label :download, "Attachment (Optional)" %>
        <div class="control">
          <%= f.file_field :download %>
        </div>
      </div>
      <%= f.hidden_field :length_in_seconds %>
      <%= f.hidden_field :wistia_id %>
      <%= f.hidden_field :wistia_delivery_id %>
      <%= f.hidden_field :section_id, value: @section.id %>
      <div class="field">
        <div class="control">
          <%= f.submit "Submit", class: "button is-primary", id: "video-submit" %>
        </div>
      </div>
    <% end %>
    <div class="columns">
      <div class="column">
      <br>
        <%= button_to "Delete Video", video_path(@video), method: :delete, class: "button is-danger", data: { confirm: "Are you sure?"} %>
      </div>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<%= render 'shared/videos' %>
<div class="columns">
  <div class="column is-offset-4" >
    <%= paginate @videos %>
  </div>
</div>

app/views/videos/new.html.erb
<% provide(:title, "Upload") %>
<script src="//fast.wistia.com/assets/external/api.js" async></script>
<link rel="stylesheet" href="//fast.wistia.com/assets/external/uploader.css" />
<% if @video.errors.any? %>
  <ul>
    <% @video.errors.full_messages.each do |msg| %>
      <li class="notification is-danger"><%= msg %></li>
    <% end %>
  </ul>
  <br>
<% end %>
<div class="columns">
  <div class="column is-6-desktop is-12-mobile">
    <%= form_for [@section, @video] do |f| %>
      <div class="field">
        <div class="control">
          <%= f.text_field :title, class: "input", placeholder: "Title" %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.text_area :description, class: "textarea", placeholder: "Short Video Description" %>
        </div>
      </div>
      <div class="field">
        <%= wistia_uploader %>
      </div>
      <div class="field">
        <%= f.label :download, "Attachment (Optional)" %>
        <div class="control">
          <%= f.file_field :download%>
        </div>
      </div>
      <%= f.hidden_field :length_in_seconds %>
      <%= f.hidden_field :wistia_id %>
      <%= f.hidden_field :wistia_delivery_id %>
      <div class="field">
        <div class="control">
          <%= f.submit "Submit", class: "button is-primary", id: "video-submit", disabled: true %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
window._wapiq = window._wapiq || [];
_wapiq.push(function(W) {
  window.wistiaUploader = new W.Uploader({
    accessToken: '7583b7e3465fbaaa70163ab255a0f9581b9817755d4dac04d4b75556c5e61da9',
    dropIn: "wistia_uploader",
    projectId: document.getElementById("wistia_uploader").dataset.project,

    extraVideoExtensions: 'mkv'
  });
  wistiaUploader.bind("uploadembeddable", function(file, media, embedCode, oembedResponse) {
    console.log("Here's the media in Wistia: ", media);
    addMediaInfo(media); // save the embed code to your database to display the video in the future
    $("#video-submit").prop("disabled", false);

  });

});
</script>
<script>
  function addMediaInfo(media) {
    document.getElementById("video_wistia_id").value = media.id;
    document.getElementById("video_length_in_seconds").value = Math.round(media.attributes.duration);
    document.getElementById("video_wistia_delivery_id").value = extractHash(media.thumbnail.url);
  }

  function extractHash(thumbnailUrl) {
    return thumbnailUrl.slice(40, 80);
  }
</script>

app/views/videos/show.html.erb
<% provide(:title, @video.title) %>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script>

<div class="columns video-page">
  <div class="column video-column is-10 is-offset-1">
    <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;">
      <div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;">
        <%= content_tag(:div, " ",
                        class: "wistia_embed wistia_async_#{@video.wistia_id} autoPlay=true",
                        id: "wistia_vid",
                        style: "height:100%;width:100%",
                        data: { video_id: @video.wistia_id }) %>
      </div>
    </div>
    <br>
    <% if @video.download.file? %>
      <div class="columns">
        <div class="column">
          <span class="icon">
            <%= fa_icon "download" %>
          </span>
          <%= link_to @video.download_file_name, download_video_path(@video) %>
        </div>
      </div>
    <% end %>
    <div class="columns lesson-nav">
      <div class="column is-4 lesson">
            <%= link_to("Prev: #{@video.higher_item.title}", 
              video_path(@video.higher_item), 
              class: "link is-5") unless @video.first? %>
      </div>
      <div class="column is-4 lesson current-lesson">
        <span class="title is-4"><%= @video.title %></span>
      </div>
      <div class="column is-4 lesson next-lesson">
        <%= link_to("Next: #{@video.lower_item.title}", video_path(@video.lower_item)) unless @video.last? %>
      </div>
    </div>

    <hr>
    <div class="columns">
      <div class="column">
        <nav class="video-info breadcrumb has-succeeds-separator">
          <ul>
            <li>
              <%= link_to user_path(@video.user), class: "instructor-link" do %>
                <%=image_tag @video.user.image, size: "20x20", class: "rounded-profile" %>&nbsp;
                <%= @video.user.full_name %>
              <% end %>
            </li>
            <li>
              <%= link_to @course.title, course_path(@course) %>
            </li>
            <% if @course.sections.many? %>
              <li>
                <%= link_to section_header(@video.section), section_path(@video.section) %>
              </li>
            <% end %>
            <li class="is-active">
              <%= link_to @video.title, "#" %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <% if @video.user == current_user %>
      <div class="columns">
        <div class="column">
          <%= link_to "Edit Video", edit_video_path(@video) %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<%= form_with model: Play.new, id: "play" do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :video_id, value: @video.id %>
  <%= f.hidden_field :length_in_seconds, value: 0, id: "length_in_seconds" %>
<% end %>

<script>
counter = 0;
var video_id = document.getElementById("wistia_vid").dataset.videoId;
console.log(video_id)
window._wq = window._wq || [];
_wq.push({ id: video_id, onReady: function(video) {
  console.log("I got a handle to the video!", video);
  video.bind("secondchange", function(s) {
    incrementCounter();
  });
}});

function incrementCounter() {
  counter++;
  console.log(counter);
  if (counter == 10) {
    sendPlayUpdate(counter);
    counter = 0;
  }
}

function sendPlayUpdate(count) {
  var form = document.getElementById("play");
  var countInput = document.getElementById("length_in_seconds");
  countInput.value = parseInt(count);
  if (form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })) !== false) {
  form.submit()
  }
}

</script>