config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'courses#index'

  get '/about', to: 'static#about'
  get '/eula', to: 'static#eula'
  get '/terms', to: 'static#terms'
  get '/paymentaddendum', to: 'static#paymentaddendum'
  get '/privacy', to: 'static#privacy'
  get '/contact', to: 'static#contact'
  get '/license_agreement', to: 'static#license_agreement'
  get 'getting_paid', to: 'static#getting_paid'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'login', to: 'sessions#new'
  # get 'logout', to: 'sessions#destroy'
  get 'account', to: 'users#account'
  get 'profile', to: 'users#show'
  get 'search', to: 'videos#search'
  get 'test_login', to: 'sessions#test_login'
  get 'instructor_agreement', to: 'static#instructor_agreement'
  # get 'videos', to: 'videos#index'
  # get 'videos/new', to: 'videos#new', as: 'new_video'
  # post 'videos', to: 'videos#create'

  get 'sessions/:id', to: 'sessions#impersonate'


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :courses, shallow: true do
      member do
        post 'toggle_approval'
      end
      resources :sections do
        resources :videos do
          member do
            post 'toggle_approval'
          end
        end
      end
    end
    get 'sessions/:id', to: 'sessions#impersonate', as: "impersonate"
    get 'videos', to: 'videos#index'
  end

  resources :users
  resources :charges

  resources :plays
  resources :payments, only: [:new, :create]
  resources :courses, shallow: true do
    resources :sections do
      resources :videos do
        member do
          get 'download'
        end
      end
    end
  end

end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :user
  has_many :sections, dependent: :destroy
  has_many :videos, through: :sections


  def minutes
    videos.sum(:length_in_seconds)/60
  end
end

app/views/shows/_form.html.erb
<%= form_for @show do |f| %>
  <%= render 'shared/error_messages', object: @show %>
  <div class="field">
    <%= f.label :title, class: "label" %>
    <div class="control">
      <%= f.text_field :title, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :description, class: "label" %>
    <div class="control">
      <%= f.text_area :description, class: "textarea" %>
    </div>
  </div>
  <div class="field">
    <button type="button">Add Module</button>
  </div>
  <div class="field">
    <div class="control">
      <%= f.submit "Create Course", class: "button is-primary" %>
    </div>
  </div>
<% end %>

app/views/shows/show.html.erb
<p class="title"><%= @show.title %></p>
<% @sections.each do |section| %>
  <div class="columns">
    <div class="column list-item is-10-desktop">
      <%= link_to section_path(section) do %>
        <div class="card">
          <div class="card-content section_info">
            <span>
              <%= section_header(section) %>
            </span>
            <span>
              
            </span>
            <span>
              <%= youtube_time(section.length_in_seconds) %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
    <% if @show.user == current_user %>
      <div class="column is-2-desktop">
        <%= link_to "Edit", edit_section_path(section) %> | 
        <%= link_to "Delete", section, method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
  <% end %>
  </div>
  
<% end %>

<% if @show.user == current_user %> 
  <div class="columns">
    <div class="column">
      <%= link_to "Add Module", new_show_section_path(@show), class: "button is-primary" %>
      <div>
        <br>
        <%= link_to "Edit Course", edit_show_path(@show) %> | 
        <%= link_to "Delete Course", @show, method: :delete %>
      </div>
    </div>
  </div>
<% end %>