config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'courses#index'

  get '/about', to: 'static#about'
  get '/eula', to: 'static#eula'
  get '/terms', to: 'static#terms'
  get '/paymentaddendum', to: 'static#paymentaddendum'
  get '/privacy', to: 'static#privacy'
  get '/contact', to: 'static#contact'
  get '/license_agreement', to: 'static#license_agreement'
  get 'getting_paid', to: 'static#getting_paid'

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'login', to: 'sessions#new'
  # get 'logout', to: 'sessions#destroy'
  get 'account', to: 'users#account'
  get 'profile', to: 'users#show'
  get 'search', to: 'videos#search'
  get 'test_login', to: 'sessions#test_login'
  get 'instructor_agreement', to: 'static#instructor_agreement'
  # get 'videos', to: 'videos#index'
  # get 'videos/new', to: 'videos#new', as: 'new_video'
  # post 'videos', to: 'videos#create'

  get 'sessions/:id', to: 'sessions#impersonate'


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :courses, shallow: true do
      member do
        post 'toggle_approval'
      end
      resources :sections do
        resources :videos do
          member do
            post 'toggle_approval'
          end
        end
      end
    end
    get 'sessions/:id', to: 'sessions#impersonate', as: "impersonate"
    get 'videos', to: 'videos#index'
  end

  resources :users
  resources :charges

  resources :plays
  resources :payments, only: [:new, :create]
  resources :courses, shallow: true do
    resources :sections do
      resources :videos do
        member do
          get 'download'
        end
      end
    end
  end

end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user

  def self.create_from_transaction(transaction, user)
    seconds = Rails.configuration.rate * transaction.amount.to_i

    create!(
    seconds: seconds,
    gateway_charge_id: transaction.id,
    amount: transaction.amount.to_i,
    user_id: user.id
   )
  end

  def dollars
    amount * 100
  end
end

app/controllers/admin/charges_controller.rb
module Admin
  class ChargesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Charge.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Charge.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_amount, only: [:new, :create]
  before_action :authenticate_user!

  def new
    @charge = Charge.new
    @client_token = Braintree::ClientToken.generate
  end

  def index
  end

  def create
    result = attempt_sale(@amount, params[:nonce])
    puts result

    if result.success?
      puts "success!: #{result.transaction.id}"
      Charge.create_from_transaction(result.transaction, current_user)
      current_user.credit_purchase!(@amount)
      flash[:success] = "Purchase successful! You're balance has been updated"
      redirect_to root_url
    elsif result.transaction
      log_error(result)
      flash[:danger] = "Payment could not be processed"
      redirect_to new_charge_path
    else
      p result.errors
      flash[:danger] = "Payment could not be processed"
      redirect_to new_charge_path
    end
  end

  private

  def attempt_sale(amount, nonce)
    Braintree::Transaction.sale(
      amount: amount,
      payment_method_nonce: nonce,
      options: {
        submit_for_settlement: true
      }
    )
  end

  def log_error(result)
    puts "Error processing transaction:"
    puts "  code: #{result.transaction.processor_response_code}"
    puts "  text: #{result.transaction.processor_response_text}"
  end

  def set_amount
    @amount = 10
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
<% provide(:title, "Buy") %>
<script src="https://js.braintreegateway.com/web/dropin/1.3.1/js/dropin.min.js"></script>
<div class="columns">
  <div class="column is-6-desktop">
    <h3 class="title is-3">500 Minutes for $10</h3>
    <p class="sales-message">Browzable Minutes allow you to view any course on the site. As you watch, minutes will be deducted from your balance. Valid for a full year. </p><br>
    <div id="dropin-container">
    </div>
    <%= form_tag charges_path, id: "charge-form" do %>
      <%= hidden_field_tag 'nonce' %>
      <%= button_tag "Pay $10", type: "button", id: "submit-button", class: "button is-primary is-large" %>
    <% end %>
  </div>
</div>

<script>
    var button = document.querySelector('#submit-button');

    braintree.dropin.create({
      authorization: "<%= @client_token %>",
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function () {
        instance.requestPaymentMethod(function (err, payload) {
          if (err) {
            console.log(err);
          } else {
            $("input[name='nonce']").val(payload.nonce);
            $("#charge-form").submit();
          }
        });
      });
    });
  </script>